env = Environment(tools = ['xpcc'], toolpath = ['../xpcc/scons/site_tools'])

# find all source files
files = env.FindFiles(
	path = [
		'.',
		])

# build the xpcc library
library = env.XpccLibrary()

env.Append(CPPPATH = '.')

# build the program
program = env.Program(
		target = env['XPCC_CONFIG']['general']['name'],
		source = files.sources)

env.Defines()

env.Alias('lib', library)
env.Alias('build', program)
env.Alias('size', env.Size(program))
env.Alias('symbols', env.Symbols(program))

hexfile = env.Hex(program)
#eepromfile = env.Eeprom(program)
env.Alias('program', 'build')
#env.Alias('program', env.Avrdude(hexfile, eepromfile))
env.Alias('program', env.Avrdude(hexfile))
env.Alias('fuse', env.AvrdudeFuses())

env.Alias('build', hexfile)
#env.Alias('build', eepromfile)
env.Alias('build', env.Listing(program))

env.Alias('all', ['build', 'size'])
 
env.Default('all')
